---
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - python3
      - python3-pip
before_install:
  - pip3 install --user --requirement requirements.txt
install:
#  - pip install --upgrade pip
script:
  # Checks all *.md files with aspell.
  # The number of spelling mistakes that are allowed.
  # Test will work properly when dictionary is large enough
  # Currently not in use. Enable when there is a proper plan
  # for usage
  #- bash tests/aspellcheck.bash 10000

  # Testing if there are any warnings
  - bash tests/checkwarnings.bash
  # Testing if the build works
  - bash tests/checkbuild.bash
