site_name: Docs CSC
# repo_url: "https://github.com/CSCfi/csc-user-guide/"
# repo_url: false
edit_uri: "https://github.com/CSCfi/csc-user-guide/edit/develop/docs"
nav: 
  - Home: index.md
  - Accounts:
     - Creating new user account: accounts/creating-new-user-account.md
     - Getting student accounts for course: accounts/getting-student-accounts-for-course.md
     - Getting machine-to-machine robot accounts: accounts/getting-machine-to-machine-robot-accounts.md
     - Getting account without Haka or Virtu: accounts/getting-account-without-haka-or-virtu.md
     - Getting access to Pouta: accounts/get-access-to-pouta.md
     - Changing password: accounts/changing-password.md
     - Managing user information: accounts/managing-user-information.md
     - Joining project: accounts/joining-project.md
     - Creating new project: accounts/creating-new-project.md
     - Adding members to project: accounts/adding-members-to-project.md
     - Adding service access for project: accounts/adding-service-access-for-project.md
     - Applying for resources: accounts/applying-for-resources.md
     - Switching between projects: accounts/switching-between-projects.md
     - Monitoring resource usage: accounts/monitoring-resource-usage.md
  - Connecting: 
     - Connecting to CSC: connecting/index.md
  - Computing: 
#     - Overview: computing/index.md
     - Module system: computing/module-system.md
     - Resource monitoring: computing/resource-monitoring.md
     - Available compilers: computing/available-compilers.md
     - Using MPI: computing/using-MPI.md
     - Shared memory and hybrid parallelization: computing/shared-memory-and-hybrid-parallelization.md
     - Debugging parallel applications: computing/debugging-parallel-applications.md
     - GPU module environment: computing/gpu-modules.md
     - Compiling GPU programs: computing/Building-GPU-programs.md
     - Running GPU programs: computing/running-gpu-programs.md
     - Interactive jobs (Puhti-shell): computing/shell.md
     - Interactive batch jobs: computing/interactive-batch-jobs.md
     - Advanced batch jobs: computing/advanced-batch-jobs.md
     - Disk environment: computing/disk-environment.md
     - FGCI-guide: computing/fgci-guide-intro.md
  - Cloud:
     - Concepts of cloud computing: cloud/concepts.md
     - Pouta:
#        - Contents: cloud/pouta/index.md
        - What is Pouta: cloud/pouta/pouta-what-is.md
        - Applying for Pouta Access: accounts/get-access-to-pouta.md
        - Security Guidelines for Pouta: cloud/pouta/security.md
        - Pouta Accounting Principles and Quotas: cloud/pouta/accounting.md
        - Virtual machine flavors and Billing Unit rates: cloud/pouta/vm-flavors-and-billing.md
        - Getting started with Pouta:
            - Launching a virtual machine with the cPouta web interface: cloud/pouta/launch-vm-from-web-gui.md
            - Connecting to your virtual machine: cloud/pouta/connecting-to-vm.md
            - Install command line tools: cloud/pouta/install-client.md
            - Command line client tools: cloud/pouta/command-line-tools.md
            - Virtual machine lifecycle & saving billing units: cloud/pouta/vm-lifecycle.md
        - Storage in Pouta:
            - Available storage options: cloud/pouta/storage.md
            - Ephemeral storage: cloud/pouta/ephemeral-storage.md
            - Persistent volumes: cloud/pouta/persistent-volumes.md
            - Snapshots: cloud/pouta/snapshots.md
        - Object storage:
            - Description: cloud/pouta/object-storage-main.md
            - Common use cases: cloud/pouta/object-storage-use-cases.md
            - Using object storage: cloud/pouta/using-object-storage.md
            - Access the object storage from Taito: cloud/pouta/access-pouta-object-storage-from-taito.md
            - Quotas and billing: cloud/pouta/object-storage-quotas-and-billing.md
            - Common Error Messages: cloud/pouta/object-storage-error-msgs.md
        - Images: cloud/pouta/adding-images.md
        - Orchestration with Heat: cloud/pouta/heat-orchestration.md
        - Container Orchestration in cPouta: cloud/pouta/pouta-container-orchestration.md
        - Application Development Practises in Pouta: cloud/pouta/application-dev.md
        - Additional services in Pouta (email, dns): cloud/pouta/additional-services.md
        - Pouta videos: cloud/pouta/pouta-videos.md
        - Known problems and limitations: cloud/pouta/known-problems.md
        - FAQ: /support/faq#pouta
     - Rahti:
        - Introduction:
           - Background: cloud/rahti/introduction/background.md
           - Service description: cloud/rahti/introduction/service_description.md
           - SLA: cloud/rahti/introduction/sla.md
           - Technical maturity: cloud/rahti/introduction/technical_maturity.md
           - Getting access: cloud/rahti/introduction/access.md
           - Resource billing: cloud/rahti/introduction/billing.md
        - Usage:
           - Getting started: cloud/rahti/usage/getting_started.md
           - Projects and Quota: cloud/rahti/usage/projects_and_quota.md
           - Security guide: cloud/rahti/usage/security-guide.md
           - Command line tools: cloud/rahti/usage/cli.md
        - External documentation:
           - Platform documentation: cloud/rahti/ext_docs.md
        - Tutorials:
           - Deploying applications from web console: cloud/rahti/tutorials/basic-console.md
           - Core objects: cloud/rahti/tutorials/elemental_tutorial.md
           - Utility objects: cloud/rahti/tutorials/advanced_tutorial.md
           - Design patterns: cloud/rahti/tutorials/patterns.md
        - Support: 
           -  Contact support: cloud/rahti/contact.md
  - Data:
     - Moving data:
        - Copying files using scp: data/scp.md
        - Graphical file transfer tools: data/graphical_transfer.md
        - Using rsync for data transfer and synchronization: data/rsync.md
        - Using wget to download data from web sites to CSC: data/wget.md
        - Sharing and transporting files using Funet FileSender: data/funet.md
        - Remote disk mounts: data/disk_mount.md
     - Allas object storage:
        - Introduction to Allas Storage service: data/Allas/introduction.md
        - Accessing Allas: data/Allas/accessing_allas.md
        - Common Use Cases: data/Allas/using_allas/common_use_cases.md
        - Allas Clients: data/Allas/clients.md
        - Common Error Messages: data/Allas/using_allas/error_messages.md
        - Further information: data/Allas/further_info.md
        - cPouta object storage and Allas: data/Allas/allas_cpouta_change.md
  - Applications: 
     - By discipline: apps/index.md
     - In alphabetic order: apps/alpha.md
  - Support:
     - Tutorials: support/tutorials.md
     - FAQ: support/faq.md
     - Contact: support/contact.md

theme:
  name: windmill
  custom_dir: mkdocs_csc
extra:
  logo: img/CSC_LOGO_nega_pad.png
  article_nav: false
  footer: false
extra_css:
  - css/extra.css
extra_javascript:
  - https://use.fontawesome.com/e51b07f7f1.js
markdown_extensions:
  - toc:
      toc_depth: 2-6
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.snippets
