site_name: Docs CSC
edit_uri: "https://github.com/CSCfi/csc-user-guide/edit/master/docs"
nav:
  - Home: index.md
  - Accounts:
     - Overview: accounts/overview.md
     - How to create new user account: accounts/how-to-create-new-user-account.md
     - How to change password: accounts/how-to-change-password.md
     - How to manage user information: accounts/how-to-manage-user-information.md
     - How to create new project: accounts/how-to-create-new-project.md
     - How to add member to project: accounts/how-to-add-member-to-project.md
     - How to add service access for project: accounts/how-to-add-service-access-for-project.md
     - How to apply for resources: accounts/how-to-apply-for-resources.md
     - How to switch between projects: accounts/how-to-switch-between-projects.md
     - Billing: accounts/billing.md
     - FMI: accounts/FMI.md
  - Computing:
     - Overview: computing/overview.md
     - Systems: computing/system.md
     - Disk areas: computing/disk.md
     - Module environment: computing/modules.md
     - Running jobs: 
        - Getting started: computing/running/getting-started.md
        - Creating a batch job script: computing/running/creating-job-scripts.md
        - Submitting a job: computing/running/submitting-jobs.md
        - Available batch job partitions: computing/running/batch-job-partitions.md
        - Array jobs: computing/running/array-jobs.md
        - Example job scripts: computing/running/example-job-scripts.md
     - Compiling: computing/compiling.md
#     - Debugging: computing/debugging.md
#     - Performance analysis: computing/performance.md
  - Applications:
     - In alphabetic order: apps/alpha.md
     - By discipline: apps/index.md
  - Support:
     - Tutorials: support/tutorials.md
     - Contact: support/contact.md
theme:
  name: windmill
  custom_dir: mkdocs_csc
extra:
  logo: img/CSC_LOGO_nega_pad.png
  article_nav: false
  footer: false

extra_css:
  - css/extra.css
extra_javascript:
  - https://use.fontawesome.com/e51b07f7f1.js
markdown_extensions:
  - toc:
      toc_depth: 2-6
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.snippets
