site_name: CSC computing and data environment
repo_url: "https://github.com/CSCfi/csc-user-guide/"
edit_uri: "https://github.com/CSCfi/csc-user-guide/edit/develop/docs"
nav:
  - Home: index.md
  - Accounts:
     - Contents: accounts/index.md
     - Getting access to CSC services:
        - Creating a new user account: accounts/creating-a-new-user-account.md
        - Getting student accounts for a course: accounts/getting-student-accounts-for-a-course.md
        - Getting machine-to-machine robot accounts: accounts/getting-machine-to-machine-robot-accounts.md
        - Getting accounts for international collaborators: accounts/getting-accounts-for-international-collaborators.md
        - Getting access to Pouta: accounts/get-access-to-pouta.md
     - Managing account:
        - Changing the password: accounts/changing-the-password.md
        - Managing user information: accounts/managing-user-information.md
     - Managing projects and services:
        - Joining a project: accounts/joining-a-project.md
        - Creating a new project: accounts/creating-a-new-project.md
        - Adding members to a project: accounts/adding-members-to-a-project.md
        - Adding service access for a project: accounts/adding-service-access-for-a-project.md
     - Managing resources:
        - Applying for resources: accounts/applying-for-resources.md
        - Switching between projects: accounts/switching-between-projects.md
        - Monitoring resource usage: accounts/monitoring-resource-usage.md
  - Connecting: connecting/index.md
  - Computing: computing/index.md
  - Cloud:
     - Contents: cloud/index.md
     - Concepts of cloud computing: cloud/concepts.md
     - Security Guidelines for Pouta: cloud/security.md
     - Pouta Accounting Principles and Quotas: cloud/accounting.md
     - Virtual machine flavors and Billing Unit rates: cloud/vm-flavors-and-billing.md
     - Launching a virtual machine with the cPouta web interface: cloud/launch-vm-from-web-gui.md
     - Connecting to your virtual machine: cloud/connecting-to-vm.md
     - Command line client tools: cloud/command-line-tools.md
     - Install command line tools: cloud/install-client.md
     - Virtual machine lifecycle & saving billing units: cloud/vm-lifecycle.md
     - Orchestration with Heat: cloud/heat-orchestration.md
     - Container Orchestration in cPouta: cloud/pouta-container-orchestration.md
     - Application Development Practises in Pouta: cloud/application-dev.md
     - Available storage options: cloud/storage.md
     - Ephemeral storage: cloud/ephemeral-storage.md
     - Persistent volumes: cloud/persistent-volumes.md
     - Snapshots: cloud/snapshots.md
     - Object storage: cloud/object-storage-main.md
     - Short description of object storage: cloud/object-storage-definition.md
     - Benefits of using object storage: cloud/benefits-of-object-storage.md
     - Common use cases: cloud/object-storage-use-cases.md
     - Using Object storage: cloud/using-object-storage.md
     - Quotas and billing: cloud/object-storage-quotas-and-billing.md
     - Using object storage: cloud/using-object-storage.md
     - Access the object storage from Taito: cloud/accessing-the-pouta-object-storage-from-taito.md
     - Common Error Messages: cloud/object-storage-error-msgs.md
     - Creating and uploading virtual machine images: cloud/adding-images.md
     - Additional services in Pouta (email, dns): cloud/additional-services.md
     - Pouta videos: cloud/pouta-videos.md
     - Known problems and limitations: cloud/known-problems.md
     - cloud/access-pouta-object-storage-from-taito.md
     - cloud/application-development-in-pouta.md
     - cloud/client-usage.md
     - cloud/getting-started.md
     - cloud/pouta-user-guide.md
  - Data: data/index.md
  - Applications: apps/index.md
  - Support: support/index.md
theme:
#  name: material
#  name: readthedocs
  name: windmill
#  name: 'rtd-dropdown'
  custom_dir: custom_theme/
extra_css:
  - css/extra.css
extra_javascript:
  - https://use.fontawesome.com/e51b07f7f1.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.snippets
