site_name: CSC computing and data environment
repo_url: "https://github.com/CSCfi/csc-user-guide/"
edit_uri: "https://github.com/CSCfi/csc-user-guide/edit/develop/docs"
nav:
  - Home: index.md
  - Accounts: accounts/index.md
  - Connecting: connecting/index.md
  - Computing: computing/index.md
  - Cloud: 
     - Contents: cloud/index.md
     - Concepts of cloud computing: cloud/concepts.md
     - Pouta: 
        - Contents: cloud/pouta/index.md
        - What is Pouta: cloud/pouta/pouta-whatis.md
        - Applying for Pouta Access: accounts/get-access-to-pouta.md
        - Security Guidelines for Pouta: cloud/pouta/security.md
        - Pouta Accounting Principles and Quotas: cloud/pouta/accounting.md
        - Virtual machine flavors and Billing Unit rates: cloud/pouta/vm-flavors-and-billing.md
        - Launching a virtual machine with the cPouta web interface: cloud/pouta/launch-vm-from-web-gui.md
        - Connecting to your virtual machine: cloud/pouta/connecting-to-vm.md
        - Command line client tools: cloud/pouta/command-line-tools.md
        - Install command line tools: cloud/pouta/install-client.md
        - Virtual machine lifecycle & saving billing units: cloud/pouta/vm-lifecycle.md
        - Orchestration with Heat: cloud/pouta/heat-orchestration.md
        - Container Orchestration in cPouta: cloud/pouta/pouta-container-orchestration.md
        - Application Development Practises in Pouta: cloud/pouta/application-dev.md
        - Available storage options: cloud/pouta/storage.md
        - Ephemeral storage: cloud/pouta/ephemeral-storage.md
        - Persistent volumes: cloud/pouta/persistent-volumes.md
        - Snapshots: cloud/pouta/snapshots.md
        - Object storage: cloud/pouta/object-storage-main.md
        - Short description of object storage: cloud/pouta/object-storage-definition.md
        - Benefits of using object storage: cloud/pouta/benefits-of-object-storage.md
        - Common use cases: cloud/pouta/object-storage-use-cases.md
        - Using Object storage: cloud/pouta/using-object-storage.md
        - Quotas and billing: cloud/pouta/object-storage-quotas-and-billing.md
        - Using object storage: cloud/pouta/using-object-storage.md
        - Access the object storage from Taito: cloud/pouta/access-pouta-object-storage-from-taito.md
        - Common Error Messages: cloud/pouta/object-storage-error-msgs.md
        - Creating and uploading virtual machine images: cloud/pouta/adding-images.md
        - Additional services in Pouta (email, dns): cloud/pouta/additional-services.md
        - Pouta videos: cloud/pouta/pouta-videos.md
        - Known problems and limitations: cloud/pouta/known-problems.md
     - Rahti:
        - Contents: cloud/rahti/index.md
  - Data: data/index.md
  - Applications: apps/index.md
  - Support: support/index.md
theme:
#  name: material
#  name: readthedocs
  name: windmill
#  name: 'rtd-dropdown'
  custom_dir: custom_theme/
extra_css:
  - css/extra.css
extra_javascript:
  - https://use.fontawesome.com/e51b07f7f1.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.snippets

