site_name: CSC computing and data environment
repo_url: "https://github.com/CSCfi/csc-user-guide/"
edit_uri: "https://github.com/CSCfi/csc-user-guide/edit/develop/docs"
nav:
  - Home: index.md
  - Accounts: accounts/index.md
  - Connecting: connecting/index.md
  - Computing: computing/index.md
  - Cloud: cloud/index.md
  - Data: data/index.md
  - Applications: apps/index.md
  - Support: support/index.md
theme:
#  name: readthedocs
  name: material
#  custom_dir: custom_theme/
extra_css:
  - css/extra.css
extra_javascript:
  - https://use.fontawesome.com/e51b07f7f1.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.snippets
